import { useState } from "react";
import { FileDown, Loader2, CheckCircle2, FileText } from "lucide-react";

interface ReportConfig {
  label: string;
  key: string;
  checked: boolean;
}

const DEFAULT_SECTIONS: ReportConfig[] = [
  { label: "Farm Profile & Land Details", key: "profile",   checked: true },
  { label: "Crop AI Advisory History",    key: "advisory",  checked: true },
  { label: "Vet Consultation Records",    key: "vet",       checked: true },
  { label: "Pest Outbreak Alerts",        key: "pest",      checked: true },
  { label: "AMU Treatment Ledger",        key: "amu",       checked: false },
  { label: "Soil Sensor Readings",        key: "sensors",   checked: false },
];

interface FarmerInfo {
  name?: string;
  farmId?: string;
  soilType?: string;
  phone?: string;
}

export function PDFExport({ farmer }: { farmer?: FarmerInfo }) {
  const [sections, setSections] = useState<ReportConfig[]>(DEFAULT_SECTIONS);
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  function toggleSection(key: string) {
    setSections((s) => s.map((r) => r.key === key ? { ...r, checked: !r.checked } : r));
  }

  function generateReport() {
    const selected = sections.filter((s) => s.checked);
    if (selected.length === 0) return;

    setGenerating(true);
    setDone(false);

    // Build a printable HTML report and open in a new window
    setTimeout(() => {
      const dateStr = new Date().toLocaleDateString("en-IN", { dateStyle: "long" });
      const rows = selected.map((s) => `
        <section style="margin-bottom:2rem;padding-bottom:1rem;border-bottom:1px solid #e5e7eb">
          <h2 style="font-size:1.1rem;font-weight:600;color:#1f2937;margin-bottom:0.5rem">${s.label}</h2>
          <p style="color:#6b7280;font-size:0.9rem">
            ${
              s.key === "profile"
                ? `Farmer: ${farmer?.name ?? "N/A"} | Soil: ${farmer?.soilType ?? "N/A"} | Phone: ${farmer?.phone ?? "N/A"}`
                : s.key === "advisory"
                ? "AI-generated crop advisories for the last 30 days. (Stored advisories will appear here when database is connected.)"
                : s.key === "vet"
                ? "All consultation requests submitted to the vet panel, including responses and notes."
                : s.key === "pest"
                ? "Predictive outbreak alerts based on regional seasonal data and weather patterns."
                : s.key === "amu"
                ? "Antimicrobial usage log with hash-chained entries for compliance and audit purposes."
                : "IoT soil sensor readings — moisture, temperature, pH, and nitrogen levels."
            }
          </p>
        </section>`).join("");

      const html = `<!DOCTYPE html>
<html><head>
<meta charset="UTF-8"/>
<title>AgriVerse Farm Report — ${farmer?.name ?? "Farmer"}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #111827; }
  h1 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 0.5rem; }
</style>
</head><body>
  <h1>🌾 AgriVerse Farm Report</h1>
  <p style="color:#6b7280">Generated: ${dateStr} | Farmer: ${farmer?.name ?? "N/A"} | ID: ${farmer?.farmId ?? "N/A"}</p>
  <hr style="margin:1.5rem 0"/>
  ${rows}
  <p style="color:#9ca3af;font-size:0.8rem;text-align:center;margin-top:2rem">
    Generated by AgriVerse — Smart Farm Management System
  </p>
</body></html>`;

      const win = window.open("", "_blank");
      win?.document.write(html);
      win?.document.close();
      win?.print();

      setGenerating(false);
      setDone(true);
      setTimeout(() => setDone(false), 4000);
    }, 1200);
  }

  const selectedCount = sections.filter((s) => s.checked).length;

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <FileText className="h-5 w-5 text-indigo-400" />
          Export Farm Report
        </h3>
        <p className="text-sm text-muted-foreground mt-0.5">
          Generate a printable PDF / HTML report of your farm records.
        </p>
      </div>

      <div className="glass-card border-white/10 rounded-xl p-4 space-y-2">
        <p className="text-xs font-medium text-muted-foreground mb-3">Select sections to include:</p>
        {sections.map((s) => (
          <label key={s.key} className="flex items-center gap-2.5 cursor-pointer group">
            <input
              type="checkbox"
              checked={s.checked}
              onChange={() => toggleSection(s.key)}
              className="h-4 w-4 rounded accent-primary"
            />
            <span className="text-sm group-hover:text-foreground text-muted-foreground transition">{s.label}</span>
          </label>
        ))}
      </div>

      <button
        onClick={generateReport}
        disabled={generating || selectedCount === 0}
        className="w-full flex items-center justify-center gap-2 py-2.5 rounded-lg bg-primary text-primary-foreground font-medium text-sm disabled:opacity-50 hover:brightness-105 transition"
      >
        {generating ? (
          <><Loader2 className="h-4 w-4 animate-spin" /> Generating Report…</>
        ) : done ? (
          <><CheckCircle2 className="h-4 w-4 text-green-300" /> Report Ready — Check Print Dialog</>
        ) : (
          <><FileDown className="h-4 w-4" /> Export {selectedCount} Section{selectedCount !== 1 ? "s" : ""} as PDF</>
        )}
      </button>

      <p className="text-[11px] text-muted-foreground text-center">
        Opens your browser print dialog — choose "Save as PDF" to download.
      </p>
    </div>
  );
}
